<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>DCML.DataCenter.Persistence</AssemblyName>
    <RootNamespace>DCML.DataCenter.Persistence</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DCML.DataCenter\DCML.DataCenter.csproj" />
  </ItemGroup>

</Project>
