<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>DCML.MultiModuleProbe.Publisher</AssemblyName>
    <RootNamespace>DCML.MultiModuleProbe.Publisher</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DCML.Core\DCML.Core.csproj" />
  </ItemGroup>

</Project>
