<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>DCML.Persistence.Helper</AssemblyName>
    <RootNamespace>DCML.Persistence.Helper</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Formats.Nrbf" Version="10.0.11" />
  </ItemGroup>

</Project>
